# Generated by Django 5.2 on 2026-03-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_categoria_editorial_libro_apartado_prestamo_multa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_clave_acceso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_nombre_acceso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_rol',
        ),
    ]
