# Generated by Django 5.2 on 2026-03-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_remove_usuario_usuario_clave_acceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
