# Generated by Django 5.2 on 2026-03-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_usuario_matricula_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
