# Generated by Django 5.2 on 2026-03-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_usuario_is_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_activate',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn_normalizado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
